# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:  "Simplifying Data Science"
email: kolbymckay22@gmail.com
description: "Teaches the basics of SQL, a common programming language used to gather and organize data." 
baseurl: "/my-datascience-blog" # the name of the repository 
url: "https://kolbymckay22.github.io" #  change this to "https://<your-github-username>.github.io"
image: "assets/images/data_science_background.jpeg"
author: Kolby Taylor
copyright: KT # Your initials or name or what you want the copyright to be.  Leave empty for no copyright


# Social media users names.  Leave fields blank that you don't want displayed
twitter_username: 
github_username:  kolbymckay22
linkedin_username: 
dribbble_username: 
facebook_username: 
flickr_username:
instagram_username: 
pinterest_username:
youtube_username: 
googleplus_username: 

plugins:
  - jekyll-feed

